# org.atomicoke.mdtoc.MdTocToolProperties
name: MarkDownTocTool
version: 0.2.2
handlerClassNames:
  - org.atomicoke.mdtoc.handler.LocalFileMdTocToolArgHandler
  - org.atomicoke.mdtoc.handler.RemoteMdTocToolArgHandler
  - org.atomicoke.mdtoc.handler.VersionMdTocToolArgHandler