# @see org.atomicoke.mdtoc.MdTocToolProperties
name: MarkDownTocTool
version: 1.0.0
handlerClassNames:
  - org.atomicoke.mdtoc.handler.LocalFileMdTocToolArgHandler
  - org.atomicoke.mdtoc.handler.RemoteFileMdTocToolArgHandler
  - org.atomicoke.mdtoc.handler.VersionMdTocToolArgHandler