# org.atomicoke.mdtoc.MdTocToolProperties
name: MarkDownTocTool
version: 0.2.3
handlerClassNames:
  - org.atomicoke.mdtoc.handler.LocalFileMdTocToolArgHandler
  - org.atomicoke.mdtoc.handler.RemoteFileMdTocToolArgHandler
  - org.atomicoke.mdtoc.handler.VersionMdTocToolArgHandler